### ISSUE TITLE
Failed to compile with UE 5.6 for macOS 15.5 Xcode 16.4

### ISSUE THREAD

**Issue by Zubius** [Megafunk/MassSample#80]
When trying to compile the fresh repo I have an error 

`0>[1/4] Link [Apple] UnrealEditor-MassCommunitySample.dylib
0>duplicate symbol '_GPrivateEntityManagerPointer' in:
0>/Users/zubius/projects/unreal/MassSample/Plugins/MassCommunitySample/Intermediate/Build/Mac/arm64/UnrealEditor/Development/MassCommunitySample/MSPhysicsInitProcessors.cpp.o
0>/Users/zubius/projects/unreal/MassSample/Plugins/MassCommunitySample/Intermediate/Build/Mac/arm64/UnrealEditor/Development/MassCommunitySample/Module.MassCommunitySample.cpp.o
0>ld: 1 duplicate symbols
0>clang++: Error  : linker command failed with exit code 1 (use -v to see invocation)`
