### ISSUE TITLE
Sample project does not compile in UE 5.2.1

### ISSUE THREAD

**Issue by allora** [Megafunk/MassSample#58]
This reflects some experiences in experimenting with my own code. While trying to compile a struct derived from `FMassStateTreeTaskBase` You get the error below.

This happens in this MassSample and in Epic's City Demo, as well as in my own attempts to make a custom state tree task

Unreal 5.2.1 compile error with the sample project on this repo: state tree tasks fails with an error when trying to compile 
```
0>[2/4] Link [x64] UnrealEditor-MassCommunitySample.lib cancelled
0>[3/4] WriteMetadata MassSampleProjectEditor.target cancelled
0>[4/4] Compile [x64] Module.MassCommunitySample.cpp
0>StateTreeNodeBase.h(14): Error C4430 : missing type specifier - int assumed. Note: C++ does not support default-int
0>StateTreeNodeBase.h(29): Error C2061 : syntax error: identifier 'FStateTreeLinker'
0>MSNavMeshMoveTask.h(41): Error C3668 : 'FMassNavMeshPathFollowTask::Link': method with override specifier 'override' did not override any base class methods
```
Repro Steps:

- I simply downloaded the project (git clone and git lfs pull, etc)
- Tried to run, it said i needed to compile
- Compile fails with this error.

**Comment by allora** [comment]
Just to follow up, trying this with UE 5.1.1 and the 5.1 tag on this repo seems to work fine.

**Comment by allora** [comment]
Another follow up, my own  code seems to work fine in 5.3, so likely there's some bug in 5.2. This can probably close as it seems to be a problem in UE that has since been resolved in a later version.
